In [2]:
import numpy as np
import tensorflow as tf

In [3]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

In [6]:
W = tf.Variable(tf.random.normal([4, nb_classes]), name= 'weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')
variables = [W,b]

In [9]:
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X,W)+b)


In [10]:
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[0.9765465  0.01738606 0.0060673 ]], shape=(1, 3), dtype=float32)


In [13]:
def cost_fn(X,Y):
    logits=hypothesis(X)
    cost = -tf.reduce_sum(Y*tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    return cost_mean
print(cost_fn(x_data,y_data))

tf.Tensor(8.472164, shape=(), dtype=float32)


In [12]:
def grad_fn(X,Y):
    with tf.GradientTape() as tape:
        cost = cost_fn(X,Y)
        grads = tape.gradient(cost, variables)
        return grads
print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.22836159,  0.96776885, -0.739361  ],
       [-1.589947  ,  2.0751789 , -0.4852858 ],
       [-1.6016809 ,  2.464029  , -0.8622811 ],
       [-1.6027228 ,  2.4670808 , -0.86429524]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.23131397,  0.5978541 , -0.36654007], dtype=float32)>]


In [14]:
def fit(X,Y, epochs=2000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X,Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X,Y).numpy()))

fit(x_data, y_data)

Loss at epoch 1: 5.763749
Loss at epoch 100: 0.706546
Loss at epoch 200: 0.620419
Loss at epoch 300: 0.562362
Loss at epoch 400: 0.515883
Loss at epoch 500: 0.473977
Loss at epoch 600: 0.436936
Loss at epoch 700: 0.401386
Loss at epoch 800: 0.368524
Loss at epoch 900: 0.333213
Loss at epoch 1000: 0.302579
Loss at epoch 1100: 0.262868
Loss at epoch 1200: 0.233748
Loss at epoch 1300: 0.221166
Loss at epoch 1400: 0.210886
Loss at epoch 1500: 0.201519
Loss at epoch 1600: 0.192940
Loss at epoch 1700: 0.185002
Loss at epoch 1800: 0.177703
Loss at epoch 1900: 0.170889
Loss at epoch 2000: 0.164583


# Prediction Check

In [15]:
a = hypothesis(x_data)

print(a)
print(tf.argmax(a,1))
print(tf.argmax(y_data,1))

tf.Tensor(
[[5.5720834e-06 1.4347964e-03 9.9855965e-01]
 [6.1276573e-04 7.9903275e-02 9.1948402e-01]
 [1.7354182e-08 1.6706538e-01 8.3293462e-01]
 [1.1855685e-07 8.5085589e-01 1.4914402e-01]
 [2.6994276e-01 7.1799690e-01 1.2060314e-02]
 [1.4249223e-01 8.5743833e-01 6.9387752e-05]
 [7.3785204e-01 2.6209143e-01 5.6517849e-05]
 [9.0677726e-01 9.3221538e-02 1.1668226e-06]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
