In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
# keras 
# shape = (batchsize, sequence length, input demension)
# hidden size를 얼마로 할 건지에 따라 output의 shape가 달라짐
# 예를 들어) input shape가 (1,1,4)인데 hidden size를 2로 하여
# output shape가 (1,1,2)

In [3]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [5]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences =True, return_state = True)
outputs, states= rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
# outputs - 전체 sequence에 해당하는 hidden state 값
print('states: {}, shape: {}'.format(states, states.shape))
# states - sequence에 마지막 hidden state 값

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.48446986 -0.7557923 ]]], shape: (1, 1, 2)
states: [[-0.48446986 -0.7557923 ]], shape: (1, 2)


In [6]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

In [7]:
hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences =True, return_state = True)
outputs, states= rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
# outputs - 전체 sequence에 해당하는 hidden state 값
print('states: {}, shape: {}'.format(states, states.shape))
# states - sequence에 마지막 hidden state 값

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.5457474  -0.15963364]
  [-0.1447304  -0.47491777]
  [ 0.69669604 -0.82451904]
  [ 0.94223243 -0.76479083]
  [ 0.5270337   0.5918667 ]]], shape: (1, 5, 2) 

states: [[0.5270337 0.5918667]], shape: (1, 2)


In [8]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

In [9]:
hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences =True, return_state = True)
outputs, states= rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
# outputs - 전체 sequence에 해당하는 hidden state 값
print('states: {}, shape: {}'.format(states, states.shape))
# states - sequence에 마지막 hidden state 값

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.71625036 -0.5454045 ]
  [ 0.7880173  -0.72651976]
  [-0.33433524  0.32409367]
  [-0.83964944 -0.73027045]
  [ 0.7170642  -0.5989015 ]]

 [[ 0.39748147 -0.285762  ]
  [ 0.27127123  0.43496367]
  [-0.8895197  -0.33381277]
  [-0.45205334 -0.88116163]
  [-0.01070804 -0.69991523]]

 [[-0.73942924 -0.50110555]
  [-0.33124408 -0.8359082 ]
  [ 0.86077815 -0.46018115]
  [ 0.63396335  0.55493367]
  [-0.92047995 -0.00645098]]], shape: (3, 5, 2) 

states: [[ 0.7170642  -0.5989015 ]
 [-0.01070804 -0.69991523]
 [-0.92047995 -0.00645098]], shape: (3, 2)
